# Generated by Django 5.1 on 2024-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('mensage', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('tumb', models.ImageField(blank=True, null=True, upload_to='projetos')),
                ('tools', models.ManyToManyField(to='core.tool')),
            ],
        ),
    ]
